In [1]:
import pandas as pd
import numpy as np

In [2]:
from scipy.io import arff
import pandas as pd

df = pd.read_csv('C:/cc/dataset.csv')
df.head()

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                          -1              1                   1   
1                           1              1                   1   
2                           1              0                   1   
3                           1              0                   1   
4                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  Favicon  \
0                 -1              -1                           -1        1   
1                  0               1                           -1        1   
2                 -1              -1                           -1        1   
3                 -1              -1                            1        1   
4                  1               1                           -1        1   

   ...  popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0  ...            1       1             -1         -1           -1         -1   
1  ...            1       1             -1         -1            0         -1   
2  ...            1       1              1         -1            1         -1   
3  ...            1       1             -1         -1            1         -1   
4  ...           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1       1  
1             1                       1                   1       1  
2             1                       0                  -1       1  
3             1                      -1                   1       1  
4             1                       1                   1       0  

[5 rows x 31 columns]

1 - Phishing
0 - Legitimate

In [3]:
df['Result'].unique()

array([1, 0], dtype=int64)

In [4]:
print(df.shape)
df.columns

(11055, 31)


Index(['having_IPhaving_IP_Address', 'URLURL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL',
       'Redirect', 'on_mouseover', 'RightClick', 'popUpWidnow', 'Iframe',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank',
       'Google_Index', 'Links_pointing_to_page', 'Statistical_report',
       'Result'],
      dtype='object')

In [5]:
df.isnull().sum()

having_IPhaving_IP_Address     0
URLURL_Length                  0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistical_report             0
Result    

In [6]:
df1=df.iloc[:,[0,1,2,3,4,5,6,8,11,16,18,22,23,25,30]]
df1.head()

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                          -1              1                   1   
1                           1              1                   1   
2                           1              0                   1   
3                           1              0                   1   
4                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  Domain_registeration_length  HTTPS_token  \
0                 -1                           -1           -1   
1                  0                           -1           -1   
2                 -1                           -1           -1   
3                 -1                            1           -1   
4                  1                           -1            1   

   Submitting_to_email  Redirect  Iframe  age_of_domain  web_traffic  Result  
0                   -1         0       1             -1           -1       1  
1                    1         0       1             -1            0       1  
2                   -1         0       1              1            1       1  
3                    1         0       1             -1            1       1  
4                    1         0       1             -1            0       0

In [7]:
from skrules import SkopeRules
from sklearn.model_selection import train_test_split

c:\users\sujal\appdata\local\programs\python\python36\lib\site-packages\sklearn\externals\six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


In [8]:
X=df1.iloc[:,:14]
X.head()

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                          -1              1                   1   
1                           1              1                   1   
2                           1              0                   1   
3                           1              0                   1   
4                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  Domain_registeration_length  HTTPS_token  \
0                 -1                           -1           -1   
1                  0                           -1           -1   
2                 -1                           -1           -1   
3                 -1                            1           -1   
4                  1                           -1            1   

   Submitting_to_email  Redirect  Iframe  age_of_domain  web_traffic  
0                   -1         0       1             -1           -1  
1                    1         0       1             -1            0  
2                   -1         0       1              1            1  
3                    1         0       1             -1            1  
4                    1         0       1             -1            0

In [9]:
y=df1.iloc[:,14]
y

0        1
1        1
2        1
3        1
4        0
5        0
6        1
7        1
8        0
9        1
10       0
11       1
12       1
13       1
14       0
15       1
16       1
17       1
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       1
27       0
28       0
29       0
        ..
11025    0
11026    0
11027    0
11028    0
11029    1
11030    1
11031    0
11032    1
11033    0
11034    1
11035    0
11036    0
11037    1
11038    1
11039    1
11040    1
11041    0
11042    0
11043    1
11044    0
11045    0
11046    0
11047    1
11048    0
11049    1
11050    0
11051    1
11052    1
11053    1
11054    1
Name: Result, Length: 11055, dtype: int64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [12]:
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 12).fit(X_train, y_train) 
predictions = dtree_model.predict(X_test)
predictions_tr = dtree_model.predict(X_train)
print('test:',confusion_matrix(y_test, predictions))
print('test:',accuracy_score(y_test,predictions))
print('train:',confusion_matrix(y_train,predictions_tr))
print('train:',accuracy_score(y_train,predictions_tr))
print(classification_report(y_test,predictions ))

test: [[1830  254]
 [ 332 1233]]
test: 0.8394080570019183
train: [[3696  377]
 [ 648 2685]]
train: 0.8615987037537132
              precision    recall  f1-score   support

           0       0.85      0.88      0.86      2084
           1       0.83      0.79      0.81      1565

    accuracy                           0.84      3649
   macro avg       0.84      0.83      0.83      3649
weighted avg       0.84      0.84      0.84      3649



In [13]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 20, max_depth=10,max_features='auto')
rfc.fit(X_train, y_train)
predictions =rfc.predict(X_test)
predictions_tr = rfc.predict(X_train)
print('test:\n',confusion_matrix(y_test, predictions))
print('test:',accuracy_score(y_test,predictions))
print('train:\n',confusion_matrix(y_train,predictions_tr))
print('train:',accuracy_score(y_train,predictions_tr))
print(classification_report(y_test,predictions ))

test:
 [[1797  287]
 [ 302 1263]]
test: 0.8385859139490272
train:
 [[3602  471]
 [ 598 2735]]
train: 0.8556575749392384
              precision    recall  f1-score   support

           0       0.86      0.86      0.86      2084
           1       0.81      0.81      0.81      1565

    accuracy                           0.84      3649
   macro avg       0.84      0.83      0.84      3649
weighted avg       0.84      0.84      0.84      3649



In [14]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 10).fit(X_train, y_train) 
predictions =knn.predict(X_test)
predictions_tr = knn.predict(X_train)
print('test:\n',confusion_matrix(y_test, predictions))
print('test:',accuracy_score(y_test,predictions))
print('train:\n',confusion_matrix(y_train,predictions_tr))
print('train:',accuracy_score(y_train,predictions_tr))
print(classification_report(y_test,predictions ))

test:
 [[1804  280]
 [ 415 1150]]
test: 0.8095368594135379
train:
 [[3592  481]
 [ 763 2570]]
train: 0.8320280853362139
              precision    recall  f1-score   support

           0       0.81      0.87      0.84      2084
           1       0.80      0.73      0.77      1565

    accuracy                           0.81      3649
   macro avg       0.81      0.80      0.80      3649
weighted avg       0.81      0.81      0.81      3649



In [15]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=40)
scores = cross_val_score(clf, X, y, cv=5)
scores.mean()

0.7583898688376299

In [21]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(n_estimators=50, learning_rate=0.1,max_depth=8, random_state=0).fit(X_train, y_train)
predictions =gbc.predict(X_test)
predictions_tr = gbc.predict(X_train)
print('test:\n',confusion_matrix(y_test, predictions))
print('test:',accuracy_score(y_test,predictions))
print('train:\n',confusion_matrix(y_train,predictions_tr))
print('train:',accuracy_score(y_train,predictions_tr))
print(classification_report(y_test,predictions ))

test:
 [[1826  258]
 [ 300 1265]]
test: 0.8470813921622362
train:
 [[3664  409]
 [ 591 2742]]
train: 0.8649743451255738
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      2084
           1       0.83      0.81      0.82      1565

    accuracy                           0.85      3649
   macro avg       0.84      0.84      0.84      3649
weighted avg       0.85      0.85      0.85      3649



In [22]:
import joblib
filename = 'C:/cc/gbc_phishing.sav'
joblib.dump(gbc, filename)

['C:/cc/gbc_phishing.sav']

In [23]:
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
print(result)

0.8470813921622362
